name    'meltwater-incron'
version '0.3.1'
source 'http://inotify.aiken.cz'
license 'Apache License, Version 2.0'
summary 'Puppet Module for Incron'
description 'Puppet Module for Incron'
project_page 'https://github.com/meltwater/puppet-incron'
